/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "functions-test.check" instead.
 */

#include <check.h>

#line 1 "functions-test.check"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "functions.h"

START_TEST(sum_function)
{
#line 7
	fail_unless(sum(3, 2) == 5, "sum function borked");


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sum_function);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
